POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2025-03-05",
  "type": "Hospital",
  "specialist": "Hermanson",
  "diagnosisCodes": [
    "S62.5"
  ],
  "description": "Mr Jonnyboeeee is looking fire",
  "discharge": {
    "date": "2025-08-02",
    "criteria": "Johnny is looking stupid"
  }

}